config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  resources :issues do
    resources :votes
    resources :watches
    resources :comments
  end
  
  resources :votes
  resources :watches
  resources :users
  resources :comments
  resources :open_issues
  resources :my_issues
  resources :lines

  
  #Si esta registrat un Usuari
  if true
    root to: "home#show"
  else
    root to: "issues#index"
  end
end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :comment
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_action :set_line, only: [:show, :edit, :update, :destroy]

  # GET /lines
  # GET /lines.json
  def index
    @lines = Line.all
  end

  # GET /lines/1
  # GET /lines/1.json
  def show
  end

  # GET /lines/new
  def new
    @line = Line.new
  end

  # GET /lines/1/edit
  def edit
  end

  # POST /lines
  # POST /lines.json
  def create
    @line = Line.new(line_params)

    respond_to do |format|
      if @line.save
        format.html { redirect_to @line, notice: 'Line was successfully created.' }
        format.json { render :show, status: :created, location: @line }
      else
        format.html { render :new }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lines/1
  # PATCH/PUT /lines/1.json
  def update
    respond_to do |format|
      if @line.update(line_params)
        format.html { redirect_to @line, notice: 'Line was successfully updated.' }
        format.json { render :show, status: :ok, location: @line }
      else
        format.html { render :edit }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
    @line.destroy
    respond_to do |format|
      format.html { redirect_to lines_url, notice: 'Line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @line = Line.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      params.require(:line).permit(:text, :comment_id)
    end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_form.html.erb
<%= form_with(model: line, local: true) do |form| %>
  <% if line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line.errors.count, "error") %> prohibited this line from being saved:</h2>

      <ul>
      <% line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text, id: :line_text %>
  </div>

  <div class="field">
    <%= form.label :comment_id %>
    <%= form.number_field :comment_id, id: :line_comment_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lines/edit.html.erb
<h1>Editing Line</h1>

<%= render 'form', line: @line %>

<%= link_to 'Show', @line %> |
<%= link_to 'Back', lines_path %>

app/views/lines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lines</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lines.each do |line| %>
      <tr>
        <td><%= line.text %></td>
        <td><%= line.comment_id %></td>
        <td><%= link_to 'Show', line %></td>
        <td><%= link_to 'Edit', edit_line_path(line) %></td>
        <td><%= link_to 'Destroy', line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line', new_line_path %>

app/views/lines/new.html.erb
<h1>New Line</h1>

<%= render 'form', line: @line %>

<%= link_to 'Back', lines_path %>

app/views/lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @line.text %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @line.comment_id %>
</p>

<%= link_to 'Edit', edit_line_path(@line) %> |
<%= link_to 'Back', lines_path %>