config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  resources :issues do
    resources :votes
    resources :watches
    resources :comments
  end
  
  resources :votes
  resources :watches
  resources :users
  resources :comments
  resources :open_issues
  resources :my_issues
  resources :lines

  
  #Si esta registrat un Usuari
  if true
    root to: "home#show"
  else
    root to: "issues#index"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :issue
  has_many :line
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_issue
  
  # GET /comments
  # GET /comments.json
  def index
    # @comments = Comment.all
    @comments = @issue.comment.all
    respond_to do |format|
      format.html
      format.json { render json: @comments, status: :ok }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    respond_to do |format|
      format.html
      #format.json { render json: @comment, status: :ok }
      format.json {render json: @comment, status: :ok, serializer:CommentSerializer}
    end
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    # @comment.save
    # redirect_to @comment.issue
    #     respond_to do |format|
    #   format.html
    #   format.json { render json: @comment, status: :ok }
    # end
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.issue  }
        format.json { render json: @comment, status: :created }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    
    # logger.debug "Person attributes hash: #{comment_params[:text]}"
    # logger.debug "Person attributes hash: #{@comment.text}"
    # @comment.update(comment_params)
    
    
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to  @comment.issue }
        format.json { render json: @comment, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json {render json: {message: 'Comment deleted successfully'},
                          status: :ok}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
      if @comment.nil?
        respond_to do |format|
          format.json { render json: { error: 'Comment not found' },
                               status: :not_found }
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:text, :issue_id, :user_id)
    end
    
    def set_issue
        @issue = Issue.find_by(id: params[:issue_id])
        if @issue.nil?
           respond_to do |format|
            format.html
            format.json { render json: { error: 'Issue not found' },
                              status: :not_found }
            end
        end
    end
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text, id: :comment_text %>
  </div>



    <%= form.hidden_field :issue_id, id: :comment_issue_id %>

    <%= form.hidden_field :user_id, id: :comment_user_id %>
    <!--number_field-->


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', issues_path, class: "btn-back" %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Issue</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>



  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.text %></td>
        <td><%= comment.issue_id %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>


<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<p>
  <strong>Issue:</strong>
  <%= @comment.issue_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', issues_path, class: "btn-back" %>