config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  resources :issues do
    resources :votes
    resources :watches
    resources :comments
  end
  
  resources :votes
  resources :watches
  resources :users
  resources :comments
  resources :open_issues
  resources :my_issues
  resources :lines

  
  #Si esta registrat un Usuari
  if true
    root to: "home#show"
  else
    root to: "issues#index"
  end
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :user
  # belongs_to :assigned_user, :class_name => "User", foreign_key: "user_id"
  has_many :comment, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :watches, dependent: :destroy
  has_one_attached :file
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy, :vote]

  # GET /issues
  # GET /issues.json
  
  def index
    @users = User.all
    #status
    if params[:status] == "open"
      @issues = Issue.where(status: "open")
    elsif params[:status] == "onhold"
      @issues = Issue.where(status: "onhold")
    elsif params[:status] == "resolved"
      @issues = Issue.where(status: "resolved")
    elsif params[:status] == "duplicate"
      @issues = Issue.where(status: "duplicate")
    elsif params[:status] == "invalid"
      @issues = Issue.where(status: "invalid")
    elsif params[:status] == "wontfix"
      @issues = Issue.where(status: "wontfix")
    elsif params[:status] == "closed"
      @issues = Issue.where(status: "closed")
    #type
    elsif params[:kind] == "bug"
      @issues = Issue.where(kind: "bug")
    elsif params[:kind] == "enhancement"
      @issues = Issue.where(kind: "enhancement")
    elsif params[:kind] == "proposal"
      @issues = Issue.where(kind: "proposal")
    elsif params[:kind] == "task"
      @issues = Issue.where(kind: "task")
    #priority
    elsif params[:priority] == "major"
      @issues = Issue.where(priority: "major")
    elsif params[:priority] == "minor"
      @issues = Issue.where(priority: "minor")
    elsif params[:priority] == "trivial"
      @issues = Issue.where(priority: "trivial")
    elsif params[:priority] == "blocker"
      @issues = Issue.where(priority: "blocker")
    elsif params[:priority] == "critical"
      @issues = Issue.where(priority: "critical")
    #my issues
    elsif params[:my_issues] == "me"
      @issues = Issue.where(user_id: current_user.id)
    #watching
    elsif params[:watching] == "me"
      @issues = Issue.joins(:watches).where(['watches.issue_id = issues.id AND watches.user_id = ?', current_user.id])
    #order by
    elsif params[:title] == "order"
      @issues = Issue.order(:title)
    elsif params[:type] == "order"
      @issues = Issue.order(:type)
    elsif params[:priority] == "order"
      @issues = Issue.order(:priority)
    elsif params[:status] == "order"
      @issues = Issue.order(:status)
    elsif params[:votesCount] == "order"
      #@issues = Issue.joins(:votes).where(['votes.issue_id = issues.id']).order(:)
      @issues = Issue.order(:votesCount)
    elsif params[:watchers] == "order"
      @issues = Issue.order(:watchers)
    elsif params[:assigned_user] == "order"
      @issues = Issue.order(:assigned_user)
    elsif params[:created_at] == "order"
      @issues = Issue.order(:created_at)
    elsif params[:updated_at] == "order"
      @issues = Issue.order(:updated_at)
    #all
    else
      @issues = Issue.all
    end
    
    respond_to do |format|
      format.html
      format.json {render json: @issues, status: :ok, each_serializer: IndexIssueSerializer}
    end
  end
  
  # GET /issues/1
  # GET /issues/1.json
  def show
    @comments = @issue.comment.all
    @users = User.all
    @lines = Line.all
    
     respond_to do |format|
      format.html
      format.json {render json: @issue, status: :ok, serializer: ShowIssueSerializer}
    end
  end

  # GET /issues/new
  def new
    @issue = Issue.new()
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)
    #@issue.assigned_user = current_user.name
    @issue.user_id = current_user.id
    @issue.votesCount = 0
    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json {render json: @issue, status: :ok, serializer: ShowIssueSerializer}
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    
        # logger.debug "Person attributes hash: #{comment_params[:text]}"
        # logger.debug "Person attributes hash: #{@comment.text}"
        
        comment = @issue.comment.new(text: '', issue_id: @issue.id , user_id: current_user.id)
        comment.save
        
        if issue_params[:status] != @issue.status
          message = "changed status to #{issue_params[:status]}"
          line = Line.new(text: message, comment_id: comment.id)
          line.save
        end
        if issue_params[:title] != @issue.title
          message = "changed title to #{issue_params[:title]}"
          line = Line.new(text: message, comment_id: comment.id)
          line.save
        end
        if issue_params[:description] != @issue.description
          message = "edited description"
          line = Line.new(text: message, comment_id: comment.id)
          line.save
        end
        if issue_params[:kind] != @issue.kind
          message = "marked as #{issue_params[:kind]}"
          line = Line.new(text: message, comment_id: comment.id)
          line.save
        end
        if issue_params[:priority] != @issue.priority
          message = "marked as #{issue_params[:priority]}"
          line = Line.new(text: message, comment_id: comment.id)
          line.save
        end
        if issue_params[:assigned_user] != @issue.assigned_user
          message = "assigned to #{User.find(issue_params[:assigned_user]).name}"
          line = Line.new(text: message, comment_id: comment.id)
          line.save
        end
        
        
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def vote 
   @issue.votesCount = @issue.votesCount + 1
   @issue.save
   redirect_back(fallback_location: root_path)
   
  end
  
  def watch 
    
   @watch = @issue.watches.create
   w = Watch.create
   @issue.watch = w
   flash[:notice] = "CREAT"
   redirect_back(fallback_location: root_path)
   
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json {render json: {message: 'Issue deleted successfully'}, status: :ok}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      if !Issue.exists?(params[:id])
        render json: {error: 'Issue not found'}, status: :not_found if @issue.nil?
      else
        @issue = Issue.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:title, :description, :kind, :priority, :user_id, :status, :votesCount, :assigned_user, :file)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/edit.html.erb
<%= form_with(model: @issue, local: true) do |form| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>Issues</h1>
  <h2>Editing Issue</h2>

<div class="container">
  <div class="grid">
    
      <%= form.label :status %>
      <%= form.select :status, open: :open, onhold: :onhold, resolved: :resolved, duplicate: :duplicate, invalid: :invalid, wontfix: :wontfix, closed: :closed, :selected => params[@issue.kind] %>
    
      <%= form.label :title %>
      <%= form.text_field :title, id: :issue_title, value: @issue.title %>
    
      <%= form.label :description %>
      <div class="wrapper">
        <%= form.text_area :description, id: :issue_description, value: @issue.description %>
      </div>

      <%= form.label :kind %>
      <%= form.select :kind, bug: :bug, enhancement: :enhancement, proposal: :proposal, task: :task, :selected => params[@issue.kind] %>

      <%= form.label :priority %>
      <%= form.select :priority, major: :major, minor: :minor, trivial: :trivial, blocker: :blocker, critical: :critical, :selected => params[@issue.priority] %>

      <%= form.label :assigned_user %>
      <%= form.collection_select(:assigned_user, User.all, :id, :name ) %>
      
      <%= form.label :file %>
      <div>
        <%= form.file_field :file, multiple: false, direct_upload: true, class:"upload-btn-wrapper" %>
        <%=  @issue.file.attached? ? (image_tag @issue.file.representation(resize: "200x200>"), class:"attatchment") : '' %>
      </div>
      
      
    </div>
    
    <div class="actions">
      <button class="btn-create">Update</button>
      <%= link_to 'Back', issues_path, class: "btn-back" %>
    </div>
  </div>
</div>
    
<% end %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<div class="header">
  <h1>Issues</h1>
  <%= link_to 'Create issue', new_issue_path, class: "button top-right" %>
</div>

<div class="filter-container" id="issue-toolbar">
  <span class="filter-label">Filter by:</span>
  <%= link_to "All", issues_path(@issue), class: :filter %>
  <%= link_to "Open", "?status=open", class: :filter %>
  <%= link_to "My issues", "?my_issues=me", class: :filter %>
  <%= link_to "Watching", "?watching=me", class: :filter %>
</div>

<h2>Issues (1–<%= @issues.size %> of <%= @issues.size %>)</h2>

<table>
  <thead>
    <tr>
      <th><%= link_to "Title", "?title=order" %></th>
      <th title="Type" class="img-col"><%= link_to "T", "?type=order" %></th>
      <th title="Priority" class="img-col"><%= link_to "P", "?priority=order" %></th>
      <th><%= link_to "Status", "?status=order" %></th>
      <th><%= link_to "Votes", "?votes.count=order" %></th>
      <th><%= link_to "Watches", "?watches.count=order" %></th>
      <th><%= link_to "Assigned user", "?assigned_user=order" %></th>
      <th><%= link_to "Created", "?created_at=order" %></th>
      <th><%= link_to "Update", "?updated_at=order" %></th>
      <th class="img-col no-visible"></th>
      <th class="img-col no-visible"></th>
      <th class="img-col no-visible"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= link_to issue.title, issue %></td>
        <td>
          <% if issue.kind == 'bug' %>
            <%= link_to image_tag('bug.svg'), "?kind=bug" %>
          <% end %>
          <% if issue.kind == 'enhancement' %>
            <%= link_to image_tag('enhancement.svg'), "?kind=enhancement" %>
          <% end %>
          <% if issue.kind == 'proposal' %>
            <%= link_to image_tag('proposal.svg'), "?kind=proposal" %>
          <% end %>
          <% if issue.kind == 'task' %>
            <%= link_to image_tag('task.svg'), "?kind=task" %>
          <% end %>
        </td>
        <td>
          <% if issue.priority == 'minor' %>
            <%= link_to image_tag('minor.svg'), "?priority=minor" %>
          <% end %>
          <% if issue.priority == 'major' %>
            <%= link_to image_tag('major.svg'), "?priority=major" %>
          <% end %>
          <% if issue.priority == 'trivial' %>
            <%= link_to image_tag('trivial.svg'), "?priority=trivial" %>
          <% end %>
          <% if issue.priority == 'blocker' %>
            <%= link_to image_tag('blocker.svg'), "?priority=blocker" %>
          <% end %>
          <% if issue.priority == 'critical' %>
            <%= link_to image_tag('critical.svg'), "?priority=critical" %>
          <% end %>
        </td>
        <td style="height:30px">
          <% if issue.status == 'open' %>
            <%= link_to image_tag('open.jpg',style:"width:70px;height:100%"), "?status=open" %>
          <% end %>
          <% if issue.status == 'onhold' %>
            <%= link_to image_tag('on_hold.jpg', style:"width:70px;height:100%"), "?status=onhold" %>
          <% end %>
          <% if issue.status == 'resolved' %>
            <%= link_to image_tag('resolved.jpg',style:"width:70px;height:100%"), "?status=resolved" %>
          <% end %>
          <% if issue.status == 'duplicate' %>
            <%= link_to image_tag('duplicate.jpg',style:"width:70px;height:100%"), "?status=duplicate" %>
          <% end %>
          <% if issue.status == 'invalid' %>
            <%= link_to image_tag('invalid.jpg',style:"width:70px;height:100%"), "?status=invalid" %>
          <% end %>
          <% if issue.status == 'wontfix' %>
            <%= link_to image_tag('wontfix.jpg',style:"width:70px;height:100%"), "?status=wontfix" %>
          <% end %>
          <% if issue.status == 'closed' %>
            <%= link_to image_tag('closed.jpg',style:"width:70px;height:100%"), "?status=closed" %>
          <% end %>
        </td>
        <td><%= issue.votes.count %></td>
        <td><%= issue.watches.count %></td>
        <td>
          <%= link_to User.find(issue.assigned_user).name, "?my_issues=" + User.find(issue.assigned_user).name %>
        </td>
        <td><%= issue.created_at.strftime("%Y-%m-%d") %></td>
        <td>
          <% if (Time.now - issue.updated_at.time) < 3600 %>
            <%= "Since " + ((Time.now - issue.updated_at.time)/60).round.to_s  + " minuts" %>
          <% end %>
          <% if (Time.now - issue.updated_at.time) > 3600 && (Time.now - issue.updated_at.time) < 86400 %>
            <%= "Since " + ((Time.now - issue.updated_at.time)/3600).round.to_s  + " hours" %>
          <% end %>
          <% if (Time.now - issue.updated_at.time) > 86400 %>
            <%= "Since " + ((Time.now - issue.updated_at.time)/86400).round.to_s  + " days" %>
          <% end %>
        </td>
        <td><%= link_to image_tag('pen_1.svg'), edit_issue_path(issue), title: "Edit" %></td>
        <td><%= link_to image_tag('delete_1.svg'), issue, method: :delete, data: {confirm: 'Are you sure?'}, title: "Delete" %></td>
        <td>
          
          <% exist = issue.watches.find { |watch| watch.user_id == current_user.id} %>
          <% if exist %>
            <%= link_to image_tag('eye_2.svg') , issue_watch_path(issue,exist), method: :delete%>
          <% else %>
            <%= link_to image_tag('eye_2_no.svg') , issue_watches_path(issue), method: :post %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/issues/new.html.erb
<%= form_with(model: @issue, local: true) do |form| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container" style="text-align:center;margin-top:150px">
    <h1>Create issue</h1>
    
    <form method="post">
        <div class="grid">
            <%= form.label :title %>
            <%= form.text_field :title, id: :issue_title %>
    
            <%= form.label :description %>
            <div class="wrapper">
              <%= form.text_area :description, id: :issue_description %>
            </div>
    
            <%= form.label :kind %>
            <%= form.select :kind, bug: :bug, enhancement: :enhancement, proposal: :proposal, task: :task %>
    
            <%= form.label :priority %>
            <%= form.select :priority, major: :major, minor: :minor, trivial: :trivial, blocker: :blocker, critical: :critical  %>
            
            
            <%= form.label :assigned_user %>
            <% #<%= select_tag "Assigned user", options_from_collection_for_select(@users, "id", "name")  %>
            <%= form.collection_select(:assigned_user, User.all, :id, :name ) %>
                
            <%= form.label :file %>
            <div>
              <%= form.file_field :file, multiple: false, direct_upload: true, class:"upload-btn-wrapper" %>
            </div>
                  
            <%= form.hidden_field :status, id: :issue_status, value: :open %>
        </div>
        <div class="actions">
            <button class="btn-create">Create</button>
            <%= link_to 'Back', issues_path, class: "btn-back" %>
        </div>
    </form>
</div>


<% end %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

    <h1><%= @issue.title %></h1>

    <div class="grid">
      <span class="label">Title</span>
      <span><%= @issue.title %></span>
      
      <span class="label">Description</span>
      <span><%= @issue.description %></span>
      
      <span class="label">Kind</span>
      <span><%= @issue.kind %></span>
      
      <span class="label">Priority</span>
      <span><%= @issue.priority %></span>
      
      <span class="label">Status</span>
      <span><%= @issue.status %></span>
      
      <span class="label">User</span>
      <span><%= User.find(@issue.assigned_user).name %></span>
      
      <span class="label">Votes</span>
      <span>
        <%= @issue.votes.count %>
        <span>&nbsp&nbsp</span>
        <% exist = @issue.votes.find { |vote| vote.user_id == current_user.id} %>
            <% if exist %>
              <%= link_to 'Unvote', issue_vote_path(@issue,exist), method: :delete, class:"btn-link" %>
            <% else %>
              <%= link_to 'Vote', issue_votes_path(@issue), method: :post, class:"btn-link" %>
            <% end %>
      </span>
      
      <span class="label">Watches</span>
      <span>
        <%= @issue.watches.count %>
        <span>&nbsp&nbsp</span>
        <% exist = @issue.watches.find { |watch| watch.user_id == current_user.id} %>
            <% if exist %>
              <%= link_to 'Unwatch', issue_watch_path(@issue,exist), method: :delete, class:"btn-link" %>
            <% else %>
              <%= link_to 'Watch', issue_watches_path(@issue), method: :post, class:"btn-link" %>
            <% end %>
      </span>
      
      <span class="label">Attachment</span>
      <div>
        <% if @issue.attached_file.attached? %>
          <a href="<%= url_for(@issue.attached_file) %>" download >
          <% if @issue.attached_file.representable? %>
            <%= image_tag @issue.attached_file.representation(resize: "200x200>"), class:"attatchment" %>
          <% else %>
            <%= @issue.attached_file.filename %>
          <% end %>
          </a>
        <% else %>
          <span>None</span>
        <% end %>
      </div>
      
  </div>
  <div class="actions">
    
    <% if(current_user.id == @issue.user_id ) %><span><%= link_to 'Edit', edit_issue_path(@issue), class:"btn-create" %></span><% end %>
    <%= link_to 'Back', issues_path, class:"btn-back" %>
  </div>

  <div class="comments">
    <% @comments.each do |comment| %>
      <div class="comment">
        <p style="font-size: 14px ; color: #0052CC; font-weight: bold;"><%= comment.user.name %></p>
        <p><%= comment.text %></p>
        <ul>
        <% @lines.where(comment_id: comment.id).each do |line| %>
          <li><%= line.text %></li>
        <% end %>
        </ul>
        <span>
          <% if(current_user.id == comment.user_id ) %><span><%= link_to 'Edit', edit_comment_path(comment), class:"btn-link" %></span><% end %>
          <% if(current_user.id == comment.user_id ) %><span><%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn-link" %></span><% end %>
          <%= time_ago_in_words(comment.created_at) %>
        </span>
      </div>
    <% end %>
  </div>
  </br>
<%= form_for Comment.new do |f| %> 
<%= f.text_field :text , placeholder: 'What do you want to say?'%>  
<%= f.hidden_field :issue_id, :value => @issue.id %>  
<%= f.hidden_field :user_id, :value => current_user.id %>  
<%= f.submit "Create", class:"btn-link" %>
<% end %>